### ISSUE TITLE
Traversal bug in 1.1.42

### ISSUE THREAD

**Issue by jaiverma** [ShiftLeftSecurity/joern#382]
I think there is a problem in Joern in **v1.1.42**. According to the new documentation [https://docs.joern.io/upgrade-guides](https://docs.joern.io/upgrade-guides), `filter` and `where` have been swapped.

`filter` now takes a boolean predicate
```scala
filter(A => Boolean)
```
and `where` takes a traversal
```scala
where(trav: Traversal[A] => Traversal[_])
```

This was working fine upto some point but breaks in **v1.1.42**. For the example,
```c
int main() {
    char *x = malloc(1024);

    x[0] = 0;
    x[1] = 1;
    x[2] = 2;

    free(x);
    return 0;
}
```

For **v1.1.33**, everything works as expected
```scala
joern> cpg.call.name("free").where(_.argument.order(1).isIdentifier)
res2: Traversal[Call] = Traversal

joern> cpg.call.name("free").where(_.argument.order(1).isIdentifier).l
res3: List[Call] = List(
  Call(
    id -> 1000124L,
    code -> "free(x)",
    name -> "free",
    order -> 6,
    methodInstFullName -> None,
    methodFullName -> "free",
    argumentIndex -> 6,
    dispatchType -> "STATIC_DISPATCH",
    signature -> "TODO assignment signature",
    typeFullName -> "ANY",
    dynamicTypeHintFullName -> List(),
    lineNumber -> Some(12),
    columnNumber -> Some(4),
    resolved -> None,
    depthFirstOrder -> None,
    internalFlags -> None
  )
)
```

This doesn't work in **v1.1.42**
```scala
joern> cpg.call.name("free").where(_.argument.order(1).isIdentifier).l
cmd1.sc:1: type mismatch;
 found   : overflowdb.traversal.Traversal[io.shiftleft.codepropertygraph.generated.nodes.Expression]
 required: ?{def isIdentifier: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method trackingPointToAstBase in package language of type [A](a: A)(implicit f: A => overflowdb.traversal.Traversal[io.shiftleft.codepropertygraph.generated.nodes.TrackingPoint])io.shiftleft.semanticcpg.language.types.expressions.generalizations.AstNode[io.shiftleft.codepropertygraph.generated.nodes.AstNode]
 and method toAstNode in trait LowLowPrioImplicits of type [A, NodeType <: io.shiftleft.codepropertygraph.generated.nodes.AstNode](a: A)(implicit f: A => overflowdb.traversal.Traversal[NodeType])io.shiftleft.semanticcpg.language.types.expressions.generalizations.AstNode[NodeType]
 are possible conversion functions from overflowdb.traversal.Traversal[io.shiftleft.codepropertygraph.generated.nodes.Expression] to ?{def isIdentifier: ?}
val res1 = cpg.call.name("free").where(_.argument.order(1).isIdentifier).l
                                                       ^
cmd1.sc:1: value isIdentifier is not a member of overflowdb.traversal.Traversal[io.shiftleft.codepropertygraph.generated.nodes.Expression]
val res1 = cpg.call.name("free").where(_.argument.order(1).isIdentifier).l
                                                           ^
Compilation Failed
```
This should work because `isIdentifier` returns a `Traversal` and not a `Boolean`.

**Comment by mpollmeier** [comment]
Thank you for the good error report! I can reproduce and will TAL tomorrow. 
The issue is somewhat related to the change you mention, but it's actual root is cause is an ambiguous implicit conversion.

**Comment by mpollmeier** [comment]
@jaiverma this should be fixed in v1.1.43, which is being auto-released shortly.

**Comment by jaiverma** [comment]
@mpollmeier thank you, it is working in v1.1.43!
